node{
    stage("Clone Repo"){
        Git.clone_repo()
    }
    stage("Build"){
        Gradle.build()
    }
    stage("Docker Build"){
        Docker.buildImage()
    }
    stage("Docker Push"){
        Docker.pushImage()
    }
    stage("Deploy"){
    	AWS.updateService()
    }
  }